### ISSUE TITLE
use analytical solution?

### ISSUE THREAD

**Issue by stevengj** [feanor12/CircFit.jl#1]
One of the nice features of the Kasa algorithm is that it has an analytical solution; it would be nice to use that:
![image](https://user-images.githubusercontent.com/2913679/90985578-f93bae00-e54a-11ea-97cb-deea15e3f880.png)
![image](https://user-images.githubusercontent.com/2913679/90985591-0062bc00-e54b-11ea-9331-52a42ebf3a15.png)
![image](https://user-images.githubusercontent.com/2913679/90985599-09ec2400-e54b-11ea-8d7a-01bbd134bd11.png)

(Formulas from https://ieeexplore.ieee.org/document/1246564)

**Comment by stevengj** [comment]
(Note, however, that the formulas above are a bad way to compute the variances and covariances from a numerical perspective.  Better to call `var` and `cov` in the Statistics package.

**Comment by feanor12** [comment]
I agree. I just could not find time today to implement it.

**Comment by feanor12** [comment]
Here is a first version of the analytic solution. #2 
I did not include `var` and `cov` calls yet, because I wanted to check if the resulting values are correct.

How would you select the method? I tried an enum type, but I'm not sure if that is the correct way of doing the dispatch.

Feedback is appreciated.

**Comment by stevengj** [comment]
There's not much difference between a Val argument to select the method vs just having another function name.   But it's not clear to me why anyone would bother to choose a different method?

**Comment by stevengj** [comment]
> `rk = sqrt(sum(((x.-am).^2 + (y.-bm).^2)/n))`

This allocates 4 temporary arrays (vs. 1 if you used `.+` and `./`) and is technically susceptible to spurious overflow (e.g. if `x - am` is `1e200` it will give `Inf`).  Would probably be better to use:
```jl
rk = hypot(stdm(x, am, corrected=false), stdm(y, bm, corrected=false))
```
